## Task 3: Load the Dataset Using Pandas

Create a Jupyter Notebook named `iris_analysis.ipynb`.

Using Pandas:

1. Import the Pandas library.
2. Read the CSV file using `pd.read_csv()`.
3. Store the dataset in a DataFrame named `df`.
4. Display the first 5 rows.
5. Display the last 5 rows.
6. Display the number of rows and columns.
7. Display all column names.
8. Display the data types of all columns.

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("data/iris.csv")

In [3]:
df.head

<bound method NDFrame.head of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [4]:
df.tail

<bound method NDFrame.tail of      sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]>

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [5]:
!wc data/iris.csv

 151  151 3858 data/iris.csv

In [6]:
df.shape

(150, 5)

In [9]:
print(df.shape[0]) # for col
print(df.shape[1]) # for rows

150
5

In [10]:
df.columns # for columns names

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='str')

In [11]:
# for data types for all content
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

# Task 4
 Task 4: Explore and Analyze the Dataset

Use Pandas to answer the following questions:

1. How many rows and columns are in the dataset?
2. Are there any missing values? Show the number of missing values in each column.
3. Are there any duplicate rows?
4. How many unique Iris species are there?
5. How many flowers belong to each species?
6. What is the average sepal length?
7. What is the maximum petal length?
8. What is the minimum sepal width?
9. Calculate the mean of each numeric column for each species using `groupby()`.
10. Display descriptive statistics using `describe()`.

In [14]:
# question 1
df.shape # retrun (rows, colmuns)

(150, 5)

In [19]:
# question 2 : find mising values
print(df.isnull())
df.isnull().sum()

     sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [21]:
print(df.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
145    False
146    False
147    False
148    False
149    False
Length: 150, dtype: bool

In [22]:
# question 3
df.duplicated().sum()

np.int64(1)

In [23]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [25]:
df['species']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: str

In [26]:
# question 4
df['species'].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [28]:
# question5
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [29]:
# question 6
df['sepal_length'].mean()

np.float64(5.843333333333334)

In [30]:
# 
df['sepal_length'].max()

np.float64(7.9)

In [31]:
# question 7
df['petal_length'].max()

np.float64(6.9)

In [32]:
# question 8
df['sepal_width'].min()

np.float64(2.0)

In [36]:
df.groupby('species').mean()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [37]:
# Question 9
df.groupby('species').mean(numeric_only=True)

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.428         1.462        0.246
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [39]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

## Task 5: Filter and Analyze Data

Using Pandas:

1. Display all flowers where `sepal_length > 6`.
2. Display all flowers where `petal_width > 1.5`.
3. Display only the flowers belonging to the `setosa` species.
4. Find the species with the highest average petal length.
5. Sort the dataset by `sepal_length` in descending order.

In [41]:
print(df['sepal_length'] > 6)

0      False
1      False
2      False
3      False
4      False
       ...
145     True
146     True
147     True
148     True
149    False
Name: sepal_length, Length: 150, dtype: bool
The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [42]:
# question 1
df[df['sepal_length'] > 6]

     sepal_length  sepal_width  petal_length  petal_width     species
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
54            6.5          2.8           4.6          1.5  versicolor
56            6.3          3.3           4.7          1.6  versicolor
..            ...          ...           ...          ...         ...
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica

[61 rows x 5 columns]

In [44]:
# question 2
df[df['petal_width'] > 1.5]

     sepal_length  sepal_width  petal_length  petal_width     species
56            6.3          3.3           4.7          1.6  versicolor
70            5.9          3.2           4.8          1.8  versicolor
77            6.7          3.0           5.0          1.7  versicolor
83            6.0          2.7           5.1          1.6  versicolor
85            6.0          3.4           4.5          1.6  versicolor
100           6.3          3.3           6.0          2.5   virginica
101           5.8          2.7           5.1          1.9   virginica
102           7.1          3.0           5.9          2.1   virginica
103           6.3          2.9           5.6          1.8   virginica
104           6.5          3.0           5.8          2.2   virginica
105           7.6          3.0           6.6          2.1   virginica
106           4.9          2.5           4.5          1.7   virginica
107           7.3          2.9           6.3          1.8   virginica
108           6.7          2.5           5.8          1.8   virginica
109           7.2          3.6           6.1          2.5   virginica
110           6.5          3.2           5.1          2.0   virginica
111           6.4          2.7           5.3          1.9   virginica
112           6.8          3.0           5.5          2.1   virginica
113           5.7          2.5           5.0          2.0   virginica
114           5.8          2.8           5.1          2.4   virginica
115           6.4          3.2           5.3          2.3   virginica
116           6.5          3.0           5.5          1.8   virginica
117           7.7          3.8           6.7          2.2   virginica
118           7.7          2.6           6.9          2.3   virginica
120           6.9          3.2           5.7          2.3   virginica
121           5.6          2.8           4.9          2.0   virginica
122           7.7          2.8           6.7          2.0   virginica
123           6.3          2.7           4.9          1.8   virginica
124           6.7          3.3           5.7          2.1   virginica
125           7.2          3.2           6.0          1.8   virginica
126           6.2          2.8           4.8          1.8   virginica
127           6.1          3.0           4.9          1.8   virginica
128           6.4          2.8           5.6          2.1   virginica
129           7.2          3.0           5.8          1.6   virginica
130           7.4          2.8           6.1          1.9   virginica
131           7.9          3.8           6.4          2.0   virginica
132           6.4          2.8           5.6          2.2   virginica
135           7.7          3.0           6.1          2.3   virginica
136           6.3          3.4           5.6          2.4   virginica
137           6.4          3.1           5.5          1.8   virginica
138           6.0          3.0           4.8          1.8   virginica
139           6.9          3.1           5.4          2.1   virginica
140           6.7          3.1           5.6          2.4   virginica
141           6.9          3.1           5.1          2.3   virginica
142           5.8          2.7           5.1          1.9   virginica
143           6.8          3.2           5.9          2.3   virginica
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica
149           5.9          3.0           5.1          1.8   virginica

In [45]:
# question 3
df[df['species'] == 'setosa']

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.2  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.6           1.4          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa

In [52]:
# 
print(df.groupby('species')['petal_length'])

<pandas.api.typing.SeriesGroupBy object at 0xf8cc78abc680>

In [58]:
df.groupby('species')['petal_length'].mean()

species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal_length, dtype: float64

In [61]:
# df.loc[df['[species']]
df['species']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: str

In [54]:
# question 4 : Find the species with the highest average petal length.
df.groupby('species')['petal_length'].mean().idxmax()

'virginica'

In [55]:
df.sort_values(by='sepal_length')

     sepal_length  sepal_width  petal_length  petal_width    species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [57]:
# question 5
df.sort_values(by='sepal_length', ascending=False)

     sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
..            ...          ...           ...          ...        ...
41            4.5          2.3           1.3          0.3     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa

[150 rows x 5 columns]

# Task 6:
1. Create a folder called `output`.
2. Save the species-level summary statistics to `output/species_summary.csv`.
3. Save all flowers with `sepal_length > 6` to `output/filtered_iris.csv`.
4. Confirm that both files have been created successfully.

In [1]:
!pwd

/home/thamr/HOMEWORKS/first_week/iris_analysis

In [2]:
!ls -la

total 440
drwxrwxr-x 8 thamr thamr   4096 Oct  9 22:19 .
drwxrwxr-x 3 thamr thamr   4096 Oct  9 14:06 ..
drwxrwxr-x 2 thamr thamr   4096 Oct  9 14:38 data
drwxrwxr-x 7 thamr thamr   4096 Oct  9 14:08 .git
-rw-rw-r-- 1 thamr thamr    109 Oct  9 14:08 .gitignore
-rw-rw-r-- 1 thamr thamr   3205 Oct  9 19:45 instructions.txt
drwxrwxr-x 2 thamr thamr   4096 Oct  9 19:49 .ipynb_checkpoints
-rw-rw-r-- 1 thamr thamr  86517 Oct  9 19:45 iris_analysis.ipynb
drwxrwxr-x 2 thamr thamr   4096 Oct  9 22:18 output
-rw-rw-r-- 1 thamr thamr    395 Oct  9 14:17 pyproject.toml
-rw-rw-r-- 1 thamr thamr      5 Oct  9 14:08 .python-version
-rw-rw-r-- 1 thamr thamr      0 Oct  9 14:08 README.md
drwxrwxr-x 3 thamr thamr   4096 Oct  9 14:08 src
-rw-rw-r-- 1 thamr thamr   2623 Oct  9 14:47 Task2.ipynb
-rw-rw-r-- 1 thamr thamr   1549 Oct  9 22:19 Task6.ipynb
-rw-rw-r-- 1 thamr thamr 299392 Oct  9 14:17 uv.lock
drwxrwxr-x 6 thamr thamr   4096 Oct  9 14:18 .venv

In [5]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
species_summary = df.groupby('species').describe()

In [7]:
species_summary

           sepal_length                                              \
                  count   mean       std  min    25%  50%  75%  max
species
setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

           sepal_width         ... petal_length      petal_width         \
                 count   mean  ...          75%  max       count   mean
species                        ...
setosa            50.0  3.428  ...        1.575  1.9        50.0  0.246
versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326
virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026


                 std  min  25%  50%  75%  max
species
setosa      0.105386  0.1  0.2  0.2  0.3  0.6
versicolor  0.197753  1.0  1.2  1.3  1.5  1.8
virginica   0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 32 columns]

In [8]:
species_summary.to_csv('output/species_summary.csv')

In [9]:
# number 2
filtered_df = df[df['sepal_length'] > 6]

In [10]:
filtered_df

     sepal_length  sepal_width  petal_length  petal_width     species
50            7.0          3.2           4.7          1.4  versicolor
51            6.4          3.2           4.5          1.5  versicolor
52            6.9          3.1           4.9          1.5  versicolor
54            6.5          2.8           4.6          1.5  versicolor
56            6.3          3.3           4.7          1.6  versicolor
..            ...          ...           ...          ...         ...
144           6.7          3.3           5.7          2.5   virginica
145           6.7          3.0           5.2          2.3   virginica
146           6.3          2.5           5.0          1.9   virginica
147           6.5          3.0           5.2          2.0   virginica
148           6.2          3.4           5.4          2.3   virginica

[61 rows x 5 columns]

In [11]:
filtered_df.to_csv('output/filtred_iris.csv', index = False)

In [12]:
!ls -la

total 456
drwxrwxr-x 8 thamr thamr   4096 Oct  9 22:33 .
drwxrwxr-x 3 thamr thamr   4096 Oct  9 14:06 ..
drwxrwxr-x 2 thamr thamr   4096 Oct  9 14:38 data
drwxrwxr-x 7 thamr thamr   4096 Oct  9 14:08 .git
-rw-rw-r-- 1 thamr thamr    109 Oct  9 14:08 .gitignore
-rw-rw-r-- 1 thamr thamr   3205 Oct  9 19:45 instructions.txt
drwxrwxr-x 2 thamr thamr   4096 Oct  9 19:49 .ipynb_checkpoints
-rw-rw-r-- 1 thamr thamr 105732 Oct  9 22:33 iris_analysis.ipynb
drwxrwxr-x 2 thamr thamr   4096 Oct  9 22:35 output
-rw-rw-r-- 1 thamr thamr    395 Oct  9 14:17 pyproject.toml
-rw-rw-r-- 1 thamr thamr      5 Oct  9 14:08 .python-version
-rw-rw-r-- 1 thamr thamr      0 Oct  9 14:08 README.md
drwxrwxr-x 3 thamr thamr   4096 Oct  9 14:08 src
-rw-rw-r-- 1 thamr thamr   2623 Oct  9 14:47 Task2.ipynb
-rw-rw-r-- 1 thamr thamr   1549 Oct  9 22:19 Task6.ipynb
-rw-rw-r-- 1 thamr thamr 299392 Oct  9 14:17 uv.lock
drwxrwxr-x 6 thamr thamr   4096 Oct  9 14:18 .venv

In [15]:
!find . -maxdepth 3 -type f

./README.md
./.git/description
./.git/info/exclude
./.git/hooks/post-update.sample
./.git/hooks/pre-receive.sample
./.git/hooks/prepare-commit-msg.sample
./.git/hooks/update.sample
./.git/hooks/pre-applypatch.sample
./.git/hooks/fsmonitor-watchman.sample
./.git/hooks/pre-merge-commit.sample
./.git/hooks/pre-commit.sample
./.git/hooks/sendemail-validate.sample
./.git/hooks/applypatch-msg.sample
./.git/hooks/commit-msg.sample
./.git/hooks/push-to-checkout.sample
./.git/hooks/pre-push.sample
./.git/hooks/pre-rebase.sample
./.git/HEAD
./.git/config
./.venv/bin/cffi-gen-src
./.venv/bin/pydoc.bat
./.venv/bin/idna
./.venv/bin/jupyter-dejavu
./.venv/bin/wsdump
./.venv/bin/activate
./.venv/bin/jupyter-server
./.venv/bin/pybabel
./.venv/bin/jupyter-kernelspec
./.venv/bin/pyjson5
./.venv/bin/activate.xsh
./.venv/bin/jsonschema
./.venv/bin/jupyter-builder
./.venv/bin/jupyter-nbconvert
./.venv/bin/jupyter
./.venv/bin/activate.ps1
./.venv/bin/pygmentize
./.venv/bin/debugpy-adapter
./.venv/bin/f2py
./.venv/bin/send2trash
./.venv/bin/jsonpointer
./.venv/bin/jupyter-lab
./.venv/bin/numpy-config
./.venv/bin/mistune
./.venv/bin/jupyter-events
./.venv/bin/ipython3
./.venv/bin/jlpm
./.venv/bin/jupyter-execute
./.venv/bin/jupyter-labhub
./.venv/bin/jupyter-trust
./.venv/bin/jupyter-notebook
./.venv/bin/ipython
./.venv/bin/activate.nu
./.venv/bin/jupyter-troubleshoot
./.venv/bin/httpx
./.venv/bin/jupyter-run
./.venv/bin/activate_this.py
./.venv/bin/jupyter-migrate
./.venv/bin/jupyter-kernel
./.venv/bin/deactivate.bat
./.venv/bin/jupyter-labextension
./.venv/bin/activate.bat
./.venv/bin/iris-analysis
./.venv/bin/activate.fish
./.venv/bin/activate.csh
./.venv/bin/normalizer
./.venv/bin/debugpy
./.venv/CACHEDIR.TAG
./.venv/.lock
./.venv/.gitignore
./.venv/pyvenv.cfg
./.python-version
./src/iris_analysis/__init__.py
./output/species_summary.csv
./output/filtred_iris.csv
./.gitignore
./Task6.ipynb
./iris_analysis.ipynb
./.ipynb_checkpoints/iris_analysis-checkpoint.ipynb
./.ipynb_checkpoints/Task6-checkpoint.ipynb
./.ipynb_checkpoints/Task2-checkpoint.ipynb
./.ipynb_checkpoints/instructions-checkpoint.txt
./pyproject.toml
./data/iris.csv
./uv.lock
./Task2.ipynb
./instructions.txt

In [16]:
!cat output/filtred_iris.csv

sepal_length,sepal_width,petal_length,petal_width,species
7.0,3.2,4.7,1.4,versicolor
6.4,3.2,4.5,1.5,versicolor
6.9,3.1,4.9,1.5,versicolor
6.5,2.8,4.6,1.5,versicolor
6.3,3.3,4.7,1.6,versicolor
6.6,2.9,4.6,1.3,versicolor
6.1,2.9,4.7,1.4,versicolor
6.7,3.1,4.4,1.4,versicolor
6.2,2.2,4.5,1.5,versicolor
6.1,2.8,4.0,1.3,versicolor
6.3,2.5,4.9,1.5,versicolor
6.1,2.8,4.7,1.2,versicolor
6.4,2.9,4.3,1.3,versicolor
6.6,3.0,4.4,1.4,versicolor
6.8,2.8,4.8,1.4,versicolor
6.7,3.0,5.0,1.7,versicolor
6.7,3.1,4.7,1.5,versicolor
6.3,2.3,4.4,1.3,versicolor
6.1,3.0,4.6,1.4,versicolor
6.2,2.9,4.3,1.3,versicolor
6.3,3.3,6.0,2.5,virginica
7.1,3.0,5.9,2.1,virginica
6.3,2.9,5.6,1.8,virginica
6.5,3.0,5.8,2.2,virginica
7.6,3.0,6.6,2.1,virginica
7.3,2.9,6.3,1.8,virginica
6.7,2.5,5.8,1.8,virginica
7.2,3.6,6.1,2.5,virginica
6.5,3.2,5.1,2.0,virginica
6.4,2.7,5.3,1.9,virginica
6.8,3.0,5.5,2.1,virginica
6.4,3.2,5.3,2.3,virginica
6.5,3.0,5.5,1.8,virginica
7.7,3.8,6.7,2.2,virginica
7.7,2.6,6.9,2.3,virginica
6.9,3.2,5.7,2.3,virginica
7.7,2.8,6.7,2.0,virginica
6.3,2.7,4.9,1.8,virginica
6.7,3.3,5.7,2.1,virginica
7.2,3.2,6.0,1.8,virginica
6.2,2.8,4.8,1.8,virginica
6.1,3.0,4.9,1.8,virginica
6.4,2.8,5.6,2.1,virginica
7.2,3.0,5.8,1.6,virginica
7.4,2.8,6.1,1.9,virginica
7.9,3.8,6.4,2.0,virginica
6.4,2.8,5.6,2.2,virginica
6.3,2.8,5.1,1.5,virginica
6.1,2.6,5.6,1.4,virginica
7.7,3.0,6.1,2.3,virginica
6.3,3.4,5.6,2.4,virginica
6.4,3.1,5.5,1.8,virginica
6.9,3.1,5.4,2.1,virginica
6.7,3.1,5.6,2.4,virginica
6.9,3.1,5.1,2.3,virginica
6.8,3.2,5.9,2.3,virginica
6.7,3.3,5.7,2.5,virginica
6.7,3.0,5.2,2.3,virginica
6.3,2.5,5.0,1.9,virginica
6.5,3.0,5.2,2.0,virginica
6.2,3.4,5.4,2.3,virginica